    baseURL = 'https://acen34.github.io/PracticaHugo/'
languageCode = 'en-us'
title = 'Web de Jorge'

theme = "gokarna-hugo-main"

[params]
avatarAltText = "avatar"
avatarSize = "size-m"
avatarURL = "/images/yo.jpg"

[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
name = "Markdown"
pre = "<span data-feather='code'></span>"
url = "/markdown/"
weight = 2

[[menu.main]]
name = "Videojuegos"
pre = "<span data-feather='monitor'></span>"
url = "/videojuegos/"
weight = 3

[[menu.main]]
name = "TV"
pre = "<span data-feather='tv'></span>"
url = "/tv/"
weight = 4

[[menu.main]]
name = "PHP"
pre = "<span data-feather='terminal'></span>"
url = "/php/"
weight = 5

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
